# Generated by Django 5.2 on 2025-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="supportrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
