# Generated by Django 5.2 on 2025-06-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_alter_contactinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportrequest",
            options={},
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="description",
            field=models.TextField(),
        ),
    ]
