# Generated by Django 5.2 on 2025-06-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_alter_supportrequest_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportrequest",
            options={"ordering": ["-created_at"]},
        ),
    ]
