# Generated by Django 5.2 on 2025-06-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eventmain", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("registered_company", "Registered Company"),
                    ("non_profit_company", "Non-profit Company"),
                    ("government_entity", "Government Entity"),
                    ("educational_institution", "Educational Institution"),
                    ("individual", "Individual/Solo Proprietor"),
                ],
                default="individual",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="organizer",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organizer",
            name="verification_document",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization/verification/document/"
            ),
        ),
    ]
