# Generated by Django 5.2 on 2025-06-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eventmain", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="Eventmain.event",
            ),
        ),
    ]
