# Generated by Django 5.2 on 2025-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmain', '0003_alter_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='price',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_uploads/'),
        ),
    ]
