# Generated by Django 5.2 on 2025-05-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmain', '0005_alter_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_nep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_nep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
