# Generated by Django 5.2 on 2025-05-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmain', '0006_event_description_nep_event_name_nep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_date_time',
        ),
    ]
